name = "vibagen-uptime-checker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *", "0 1 * * *"]

[vars]
ADMIN_TELEGRAM_CHAT_ID = "-1003743484791"

[[d1_databases]]
binding = "DB"
database_name = "vibagen-db"
database_id = "8e46686e-0c24-456f-baca-024b6218897a"
